version: "3"
services:
  contextual_button:
    build: .
    image: contextual_button
    container_name: contextual_button
    ports:
      - 80:80
    links:
      - sos_service:sos
    depends_on:
      - sos_service
    volumes:
      - ./app:/app
  postgres_db:
    image: mdillon/postgis:9.5
    container_name: postgres_db
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
  sos_service:
    image: 52north/sos:4.3.8
    container_name: sos
    expose:
      - 8080
    ports:
      - 8080:8080
    links:
      - postgres_db:postgres
    depends_on:
      - postgres_db
